### ISSUE TITLE
Autotools, new statistical functions, unit testing

### ISSUE THREAD

**Issue by peterkuma** [infusion/udf_infusion#10]
Hi,

I don't know if you would be interested, but I have added support for building udf_infusion with autotools ([peterkuma/udf_infusion autotools](https://github.com/peterkuma/udf_infusion/tree/autotools)), and split the UDF functions into a number files - one function per file.

The change involves a few new files: `configure.ac`, `Makefile.am`, `src/Makefile.am`, most other files were autogenerated by `autoreconf -i`. It is modeled after [lib_mysqludf_skeleton](https://github.com/mysqludf/lib_mysqludf_skeleton). No code of UDF functions is modified.

`load.sql` and `unload.sql` are generated by make (`load.sql.sh` and `unload.sql.sh` in fact), which allows the user to load them manually, supplying any mysql client connection options necessary.

One can select to install only a restricted set of UDF functions by `./configure --enable-functions="..."`, which is useful on production servers when not all functions are needed.

The new installation instructions are described in the updated README.

I haven't tested enough yet, but things I tried seem to work fine - ./configure, building, loading, unloading and casual use of the UDF functions.

I also plan to write a set of unit tests for some of the statistical functions.

**Comment by peterkuma** [comment]
Hi Robert,

I have finished the work on the new statistical functions:

* percentile_cont
* percentile_disc
* corr
* stat_mode (MySQL would not allow the name "mode")

as well as the testing framework. The testing framework uses `mysqltest` (a program shipped with MySQL), and compares results to ones calculated by python (numpy). A large table of 1 mil. records is generated by random sampling for this purpose.

The new code is in the master branch of [peterkuma/udf_infusion](https://github.com/peterkuma/udf_infusion).

In addition, I have fixed `median`, so that it returns the correct interpolated value for even number of records. The new code uses the `nth_element` standard C++ function for median, as well as for the percentile_* functions. An alternative would be to write an implementation of the [quickselect](https://en.wikipedia.org/wiki/Quickselect) algorithm, but this approach seems to work fine, at least with the GNU C++ library (libstdc++).

Would you consider merging the code if I created a pull request? I mostly did not touch any other of your code except for the mentioned, although the changes look substatial due to splitting into files and the new build system. I have also rolled my own tiny implementation of an auto growing array (`src/array.c`, `src/array.h`) as an alternative to the LESS* macros. It is used by the new statistical functions and median.

The installation works (with tests passing) on Debian wheezy and Fedora 20. README is up to date with the changes in code, so everything should be ready.

**Comment by infusion** [comment]
Hi Peter,

thanks again for your awesome work! I really would love to see a pull request now, so that your current version will be the new official master and you'll be recognized as an official contributor.

I have two small questions before I would merge it: Should we ship all files generated by autoreconf or wouldn't it be better to have a cleaner codebase without all the generated files?

The other thing is the testing framework. I so much appreciate to have tests. The project is quite old and I haven't thought about adding tests back then. My new projects are published only with a test suite, so I really thank you for adding this here. I only wonder if an own test framework is better than using MySQL's own test system. What do you think?

Robert

**Comment by peterkuma** [comment]
That's really great you would consider merging.

It is true that the autogenerated files pollute the codebase somewhat, but as cloning from github is the major way of distribution, I think it is necessary to have them, because end users should not be expected to have autotools installed, and if they happen to have a different version, that could be a source of many errors (there are many issues with compatibility among autotools versions).

If you would like to recreate the files yourself, you should only need the `*.ac`, `*.am` files and the three `ax_*` files in `m4` which come from the mysqludf skeleton. The rest is from `autoreconf` and perhaps `automake` and `autoconf` as well, I don't remember the precise way how I arrived at all of them (autotools is quite cranky sometimes, so it takes multiple attempts).

**Note:** Now I just noticed that at least `config.h` is redundant as it is made by `./configure`.

The small testing system I created is actually based the one from MySQL. The problem with pure mysqltest is that you are supposed to have separate files with tests and results, which gets really confusing. In any case you need an accompanying Makefile to run mysqltest (ok, there is `mysql-test-run.pl`, which I haven't looked into much), and I based mine on lib_mysqludf_skeleton, which seemed to be only half finished. I have also checked other projects from the [UDF Repository for MySQL](http://www.mysqludf.org/), and they did not seem to  have anything too useful either. The main problem which needed to be solved was the generation of random data, and how to automatically compare results to ones calculated by python (or any other reference). Hence the small script `test2result` to run inline python in test cases, and allow for plain text results to be inlined below queries. The rest of work is done by mysqltest.

Anyway, if you know of any suitable testing framework which you would prefer, I can try to change it for that. But I did my best to keep everything to bare minimum of code, so that it is not like recreating a testing framework, but rather fulfilling the special requirements which comprehensive testing of a UDF library involves.
