### ISSUE TITLE
Median calculation

### ISSUE THREAD

**Issue by keithslater** [infusion/udf_infusion#11]
How is the median calculated if the set of numbers is even? Normally if there is an even set of number, it should take the middle of the middle 2 numbers and that is the result. From testing the median function it looks like it's just picking the first of the middle 2 numbers and returning that. 

Example
1, 3, 5, 7, 9, 10

Current function returns 5. It should return 6.

**Comment by infusion** [comment]
Fixed now, sorry for the misbehavior.

Robert
