### ISSUE TITLE
dynamic library ?

### ISSUE THREAD

**Issue by minla-ibiza** [infusion/udf_infusion#14]
Hi, 

Really great work ! :+1: 

I tried to compile the code to make a dll (usefull for those who want to try it on windows) in vain.
Can you please provide us one ?

Look, this guy did it : https://github.com/dtrebbien/lib_mysqludf_str

I’d be very grateful to you.
          Thank you very much  & best regards.

minLa

**Comment by infusion** [comment]
Hi Minla,

thanks for the suggestion. This can take until the end of the weekend. I have to install Windows in a VM and set up a little dev env for that purpose. But I think it's worthwhile and I'll add the dll's.

Robert

**Comment by infusion** [comment]
Hi Minla,

sorry for coming back so late. Daniel who published mysqlud_str was so kind to help me on that, as I crashed virtulbox and can't run Windows here. He just said, that he's almost done with the dll packaging, so stay tuned.

Robert

**Comment by infusion** [comment]
Daniel added the Windows support :)

**Comment by minla-ibiza** [comment]
Hi Robert,

Thank you and Daniel.
It works fine.
Good job guys ! :100: 

minLa
