### ISSUE TITLE
Can't find MySQL on Ubuntu 16.04 / MySQL 5.7

### ISSUE THREAD

**Issue by diffen** [infusion/udf_infusion#17]
I have a fresh install of MySQL 5.7 on Ubuntu 16.04. The `./configure` step fails with the error "Can't find mysql library"

I haven't done anything custom with where the libraries are installed. It was a simple apt install mysql-server.

The config log is here: http://pastebin.com/v0sDy8Le

**Comment by infusion** [comment]
Could you please try to install `libmysqlclient-dev`?

**Comment by diffen** [comment]
That did it. Thanks!
