### ISSUE TITLE
Possible Bug with Median

### ISSUE THREAD

**Issue by mguvu** [infusion/udf_infusion#18]
Median doesn't seem to calculate correctly in this case. See below:

`SELECT MEDIAN(testval) AS  `should be 1`
FROM (SELECT 1 AS testval
		UNION SELECT 1 AS testval
		UNION SELECT 1 AS testval
		UNION SELECT 1 AS testval
		UNION SELECT 2 AS testval
		UNION SELECT 2 AS testval) a;`

Expected value is 1, instead it is 1.5.

**Comment by mguvu** [comment]
disregard above comment. UNION removes dupes in derived table. no issue here.

**Comment by infusion** [comment]
You could have used `union all`.
