### ISSUE TITLE
Does not compile with Mariadb 10.2

### ISSUE THREAD

**Issue by laurielounge** [infusion/udf_infusion#19]
UDF_ARGS has no argument attribute_lengths.

Patch included in zip for mariadb_com.h if anyone needs it.

[mariadb_com.zip](https://github.com/infusion/udf_infusion/files/1511538/mariadb_com.zip)

**Comment by infusion** [comment]
Do you know how mariadb handles this? I mean they removed it for a reason probably.

**Comment by laurielounge** [comment]
Not literally... had an urgent need to get it going to tell you the truth sp just hacked the mardb_core.h file.

What I can tell you is that they supported attribute_lengths in 10.1. They don't seem to support it in 10.2.

So /usr/include/mysql/mariadb_com.h doesn't have it, but /usr/include/mysql/server/mysql_com.h DOES have arttribute_lengths.

/usr/include/mysql/mysql_com.h looks like;

/* Do not edit this file directly, it was auto-generated by cmake */

#warning This file should not be included by clients, include only <mysql.h>

#include <mariadb_com.h>

So it's just a pointer to the mariadb_com.h version.

Sorry, if I'd done a bit more digging around beforehand it would have helped.

Useful?

**Comment by infusion** [comment]
Hell yeah! It really helped a lot. I was searching for `attribute_lengths` occurrences and it occurs only once in the `cut` function, where it is used wrongly. It must have been `lengths` instead. Thank you so much for pointing this out. I'll fix it now, could you please check out the latest commits then and verify that it's working for you? It has not made anything wrong, but using `lenghts` is the correct way.

**Comment by laurielounge** [comment]
Latest commit now works -great work Robert!

**Comment by infusion** [comment]
Thanks for reporting! :)
