### ISSUE TITLE
Support for MySQL 8

### ISSUE THREAD

**Issue by ankane** [infusion/udf_infusion#20]
Hey @infusion, thanks for this neat project 👍 Is it possible to support MySQL 8?

It currently fails on the `make` step since`my_bool` [was changed](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html).

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DSTANDARD -DMYSQL_SERVER -I/usr/local/Cellar/mysql/8.0.12/include/mysql -g -O2 -MT udf_infusion_la-bound.lo -MD -MP -MF .deps/udf_infusion_la-bound.Tpo -c bound.c  -fno-common -DPIC -o .libs/udf_infusion_la-bound.o
bound.c:3:11: error: unknown type name 'my_bool'
DLLEXPORT my_bool bound_init(UDF_INIT *initid, UDF_ARGS *args, char *message) {
          ^
1 error generated.
```

**Comment by infusion** [comment]
Thanks for reporting this! I didn't notice they kicked out the my_bool data type. Maybe the cleanest fix is to keep using my_bool for a while and define it as a typedef for mysql >=8

**Comment by infusion** [comment]
Merci! :)
