### ISSUE TITLE
make fails: "unknown type name 'bool'"

### ISSUE THREAD

**Issue by joshlawrence** [infusion/udf_infusion#23]
Compiling udf_infusion on Debian Stretch with mysql 5.6 fails with an unknown type name error.  Here are the specs of my system:

* Linux dbx 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
* gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
* mysql  Ver 14.14 Distrib 5.6.41-84.1, for debian-linux-gnu (x86_64) using  7.0

Here is the text of the error:

```
make[2]: Entering directory '/home/josh/udf_infusion/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -DSTANDARD -DMYSQL_SERVER -I/usr/include/mysql  -g -O2 -MT udf_infusion_la-array.lo -MD -MP -MF .deps/udf_infusion_la-array.Tpo -c -o udf_infusion_la-array.lo `test -f 'array.c' || echo './'`array.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DSTANDARD -DMYSQL_SERVER -I/usr/include/mysql -g -O2 -MT udf_infusion_la-array.lo -MD -MP -MF .deps/udf_infusion_la-array.Tpo -c array.c  -fPIC -DPIC -o .libs/udf_infusion_la-array.o
In file included from array.h:4:0,
                 from array.c:1:
common.h:78:9: error: unknown type name 'bool'
 typedef bool my_bool;
         ^~~~
common.h:78:14: error: conflicting types for 'my_bool'
 typedef bool my_bool;
              ^~~~~~~
In file included from common.h:70:0,
                 from array.h:4,
                 from array.c:1:
/usr/include/mysql/mysql.h:53:14: note: previous declaration of 'my_bool' was here
 typedef char my_bool;
              ^~~~~~~
Makefile:452: recipe for target 'udf_infusion_la-array.lo' failed
make[2]: *** [udf_infusion_la-array.lo] Error 1
```

In searching previous issues, I see that someone ran into this problem with MySQL 8.0, but no mention of 5.6 was made.  Any tips on how to proceed?  Thank you!

**Comment by infusion** [comment]
Sorry for that issue, this is due to a fix for newer MySQL installations. Give me a few minutes

**Comment by infusion** [comment]
Okay get it. I don't know why gcc is checking the typedef since it is a version number you don't meet. I will fix it.

**Comment by joshlawrence** [comment]
> I will fix it.

Thank you very much, I appreciate it!

**Comment by infusion** [comment]
Okay, could you please check again? The problematic thing is a typedef they removed in MySQL8 and which is needed on older installations. It was fixed by checking the MySQL version number, but somehow the older version checks the validity of the typedef structure - and you don't have the C++ type "bool" on gcc.

**Comment by joshlawrence** [comment]
Just pulled and recompiled, here's the message I got this time:

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -DSTANDARD -DMYSQL_SERVER -I/usr/include/mysql -g -O2 -MT udf_infusion_la-_quantile.lo -MD -MP -MF .deps/udf_infusion_la-_quantile.Tpo -c _quantile.cc  -fPIC -DPIC -o .libs/udf_infusion_la-_quantile.o
In file included from _quantile.cc:1:0:
common.h:79:14: error: conflicting declaration 'typedef bool my_bool'
 typedef bool my_bool;
              ^~~~~~~
In file included from common.h:70:0,
                 from _quantile.cc:1:
/usr/include/mysql/mysql.h:53:14: note: previous declaration as 'typedef char my_bool'
 typedef char my_bool;
              ^~~~~~~
Makefile:704: recipe for target 'udf_infusion_la-_quantile.lo' failed
```

**Comment by infusion** [comment]
Okay, but now you used g++ instead of gcc. But anyway, what I don't get is why the line is executed at all. Could you do me a favor and give me your `MYSQL_VERSION_ID` from file `/usr/include/mysql/mysql_version.h`?

**Comment by infusion** [comment]
Nice! :) You are welcome! Glad everything works now.
