### ISSUE TITLE
the cut function can't cut multibyte string. such as Chinese

### ISSUE THREAD

**Issue by asakous** [infusion/udf_infusion#7]
ex 
SELECT cut('這是一個測試繁體中文',5) string
result
這�...

correct result should be
這是一個測...

**Comment by infusion** [comment]
hi, i'll look into that. i think checking if the cut is made place at the corner of a utf8 byte sequence should fix this, without introducing a heavy multibyte library.

**Comment by infusion** [comment]
Is working now:
```
mysql> SELECT cut('這是一個測試繁體中文',5);
+-----------------------------------------+
| cut('這是一個測試繁體中文',5)           |
+-----------------------------------------+
| 這是一個測...                           |
+-----------------------------------------+
1 row in set (0.00 sec)
```
